#!/usr/bin/env bash
# Displays information about subdomains of a domain
# shellcheck disable=SC2086
my_function () {
	value=$(dig "$2"."$1" | awk '/ANSWER SECTION/{getline; print}' | awk -F" " '{print $4,$5}')
	record=$(echo "$value" | cut -d ' ' -f1)
	destination=$(echo "$value" | cut -d ' ' -f2)
	echo "The subdomain $2 is a $record record and points to $destination"
}

if [ $# -ne 2 ]
	then
		for SUB in 'www' 'lb-01' 'web-01' 'web-02' ; do
			my_function "$1" "$SUB"
		done
	else
		my_function "$1" "$2"
fi
