#!/usr/bin/env bash
# This script that transfers a file from our client to a server
set -x
if [ $# -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

scp -T -i $4 $1 $3@$2:~/
