#!/usr/bin/env bash
# This script installs nginx on a server
sudo apt update
sudo apt -y install nginx

sudo chown -R /var/www/html/
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
