#!/usr/bin/env bash
# This script installs nginx on a server and sets up a 301 redirection
apt -y update
apt -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; }' /etc/nginx/sites-available/default
service nginx restart
