#!/usr/bin/env bash
# This script installs nginx on a server and sets up a 301 redirection and a custom 404 error page
apt -y update
apt -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; }" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "/server_name _;/a error_page 404 /404.html;" /etc/nginx/sites-available/default

sed -i "/server_name _;/a add_header X-Served-By $(hostname)" /etc/nginx/sites-available/default
service nginx restart
