#!/usr/bin/env bash
# Fizzbuzz algorithm
for ((i=1;i<=100;i++))
do
	if [ $((i%3)) -eq 0 ]
	then
		echo -n "Fizz"
	fi
	if [ $((i%5)) -eq 0 ]
	then
		echo -n "Buzz"
	fi
	if [ $((i%3)) -ne 0 ] && [ $((i%5)) -ne 0 ]
	then
		echo -n "$i"
	fi
	echo ""
done
