#!/usr/bin/env bash
# Prints section of /etc/passwd with a description
input="/etc/passwd"
while IFS=: read -r username passwd uid gid gecos home shell
do
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passwd, more info about the user here: $gecos"
done < "$input"
