#!/usr/bin/env bash
#!/usr/bin/env bash
# Print number from 1 to 20, and specific messages instead depending on value
i=1
while [ $i -le 20 ];
do
	echo $i
	if [ $i -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $i -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
	((i++))
done
