#!/usr/bin/env bash
#!/usr/bin/env bash
# Print number from 1 to 20, and specific messages instead depending on value
i=1
while [ $i -le 20 ];
do
	echo $i
	case $i in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	((i++))
done
