#!/usr/bin/env bash
# Run nginx service as the user nginx
sudo pkill -9 apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo chmod 444 /etc/nginx/nginx.conf
su -c 'service nginx start' nginx
